export const measurementsInitialState = {
  length: "",
  fNeckHt: "",
  chest: "",
  bNeckHt: "",
  shoulder: "",
  waistLoose: "",
  slvLength: "",
  slvRound: "",
  fDotPt: "",
  midAndRound: "",
  upChest: "",
  other1: "",
  other2: "",
  other3: "",
  other4: "",
};

export const inputFields = [
  {
    label: "Length",
    name: "length",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  {
    label: "F.NeckHT",
    name: "fNeckHT",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  { label: "Chest", name: "chest", maxLength: 5, keyboardType: "phone-pad" },
  {
    label: "B.NeckHT",
    name: "bNeckHT",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  {
    label: "Shoulder",
    name: "shoulder",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  {
    label: "Waist Loose",
    name: "waistLoose",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  {
    label: "SLV Length",
    name: "slvLength",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  {
    label: "SLV Round",
    name: "slvRound",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  {
    label: "F.DotPT",
    name: "fDotPt",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  {
    label: "MidH&Round",
    name: "midAndRound",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  {
    label: "UpChest",
    name: "upChest",
    maxLength: 5,
    keyboardType: "phone-pad",
  },
  { label: "Other", name: "other1", maxLength: 5, keyboardType: "phone-pad" },
  { label: "Other", name: "other2", maxLength: 5, keyboardType: "phone-pad" },
  { label: "Other", name: "other3", maxLength: 5, keyboardType: "phone-pad" },
  { label: "Other", name: "other4", maxLength: 5, keyboardType: "phone-pad" },
];

export const pickerSelection = [
  "N-Blouse Wo L",
  "N-Blouse Wt L",
  "N-Blouse Wt L",
  "D-Blouse Wo L",
  "D-Blouse Wt L",
  "Aari Blouse",
  "N-Chudi",
  "S-Chudi-St cut",
  "S-Chudi-get cut",
  "H-Emb",
  "M-Emb",
  "Saree-Side st",
  "Saree Fal st",
  "Saree Pl kt",
  "Alteration wk",
  "Lin Fab",
];
